license:
  main: apache-2.0
  additional:
    - bsd-new
    - bsd-x11
  category: Permissive
copyright:
  check: true
exclude:
  extensions:
    - yml
    - yaml
    - html
    - rst
    - conf
    - cfg
  langs:
    - HTML
